### ISSUE TITLE
got an error when run the demo

### ISSUE THREAD

**Issue by yogixRush** [drawbridge/keras-mmoe#1]
Training data shape = (10000, 100)
Validation data shape = (1000, 100)
Test data shape = (1000, 100)
Traceback (most recent call last):
  File "synthetic_demo.py", line 152, in <module>
    main()
  File "synthetic_demo.py", line 110, in main
    )(input_layer)
  File "/home/chenjw/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/chenjw/Project/WTX/mmoe/keras-mmoe-master/mmoe.py", line 175, in call
    expert_outputs = K.bias_add(x=expert_outputs, bias=self.expert_bias)
  File "/home/chenjw/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3551, in bias_add
    if len(bias_shape) != 1 and len(bias_shape) != ndim(x) - 1:
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

**Comment by alvin319** [comment]
Hi @yogixRush! Thanks for catching this issue, I've updated the `requirements.txt` and tested it myself. It seems to work fine. Let me know if this also works for you. I'll close this ticket for now and feel free to re-open it if you run into similar issues.
